### ISSUE TITLE
游戏版本v0.2.0.6，PalServerHost无法启动

### ISSUE THREAD

**Issue by Contralitary** [number201724/PalWorldSavedToDedicated#4]
更新新版本游戏后，启动PalServerHost.exe时失败，提示“PalServerHost.exe and PalServerHost.dll are placed in the PalServer directory.”

已尝试，但未能解决问题的操作：

- 本地游戏端和服务器端均进行了更新
- 重置了服务器端，从头进行了一遍操作

![Image_1712216587787](https://github.com/number201724/PalWorldSavedToDedicated/assets/130280785/978bfe01-ca8c-4ae9-a8f4-ccad9a2be20f)

**Comment by number201724** [comment]
试试最新发的v0.4呢？

**Comment by Banxiaxiala** [comment]
> 试试最新版本的v0.4呢？

佬 你这个是什么环境打包的 如何打包我想试试

**Comment by number201724** [comment]
> > 试试最新版本的v0.4呢？
> 
> 佬 你这个是什么环境打包的 如何打包我想试试

vs2022直接编译就行了

**Comment by Banxiaxiala** [comment]
> > > 试试最新版本的v0.4呢？
> > 
> > 
> > 老兄你这是什么环境资源我想尝试的如何资源资源
> 
> vs2022直接编译就行了
ok我一直在用code 现在装vs 装了一半了 我看着像c++项目我装了c++扩展
