### ISSUE TITLE
版本更新了 游戏存档入口变化了能否重新发行一个新版本

### ISSUE THREAD

**Issue by Banxiaxiala** [number201724/PalWorldSavedToDedicated#5]
strExecDir.Format( L"%s%s", strCurDir, L"\\Pal\\Binaries\\Win64" );
	strExePath.Format( L"%s\\%s", strExecDir, L"PalServer-Win64-Shipping-Cmd.exe" );

	if ( !PathFileExistsW( strExePath ) ) {
		strExePath.Format( L"%s\\%s", strExecDir, L"PalServer-Win64-Shipping.exe" );
	}

**Comment by number201724** [comment]
好 稍等

**Comment by number201724** [comment]
已更新
